name: Main
on: [push]
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Pulling to abdulm4liik.site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Pulling to the server
            cd /www/wwwroot/abdulm4liik.site/
            git checkout --ours ./
            git pull origin --force master

            # Backend Deployment (Laravel)
            cd /www/wwwroot/abdulm4liik.site/backend-AI/
            mv .env.example .env
            composer install
            php artisan optimize:clear
            php artisan config:cache
            php artisan view:cache
            php artisan optimize

            # Frontend Deployment (Vue)
            cd /www/wwwroot/abdulm4liik.site/frontend-AI/
            mv .env.example .env
            npm install
            npm run build